###
GET http://localhost:8000/

#Auth----------------------------------------------------------------------

###
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "Test1234@"
}

###
GET http://localhost:8000/auth/register

###
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "Test1234@"
}

###
GET http://localhost:8000/auth/login

###
POST http://localhost:8000/auth/logout
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
"refreshToken": "addRefreshTokenHere"
}

###
GET http://localhost:8000/auth/logout
Authorization: Bearer addAccessTokenHere

###
POST http://localhost:8000/auth/refreshToken
Content-Type: application/json

{
"refreshToken": "addRefreshTokenHere"
}

###
POST http://localhost:8000/auth/update
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "account id",
    "address": "Tel Aviv",
    "name": "test",
    "gender": "Male"
}

###
GET http://localhost:8000/auth/getAccountById/_id
Authorization: Bearer addAccessTokenHere

#Poll----------------------------------------------------------------------

###
POST http://localhost:8000/poll/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "pollName": "poll name",
    "accountId": "account test id"
}

###
GET http://localhost:8000/poll/create
Authorization: Bearer addAccessTokenHere

###
GET http://localhost:8000/poll/getAllPolls
Authorization: Bearer addAccessTokenHere

###
GET http://localhost:8000/poll/getPollsByAccountId/accountId
Authorization: Bearer addAccessTokenHere

###
POST http://localhost:8000/poll/update
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "account id",
    "gender": ["Male"],
    "minAge": "10",
    "maxAge": "20"
}


#PollQuestion----------------------------------------------------------------------

###
POST http://localhost:8000/poll_question/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "pollQuestion": "test question?",
    "pollQuestionType": "Multi Choice",
    "choices": ["q1","q2","q3"],
    "pollId": "poll id"
}

###
GET http://localhost:8000/poll_question/create
Authorization: Bearer addAccessTokenHere

###
GET http://localhost:8000/poll_question/getPollQuestionsByPollId/pollId
Authorization: Bearer addAccessTokenHere

#Detail----------------------------------------------------------------------

###
POST http://localhost:8000/detail/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "4eb6e7e7e9b7f4194e000003",
    "answer": "test answer",
    "question": "test question?",
    "questionId": "test question id",
    "accountId": "account id"
}

###
GET http://localhost:8000/detail/getDetailsByAccountId/accountId
Authorization: Bearer addAccessTokenHere

#DetailQuestion----------------------------------------------------------------------

###
POST http://localhost:8000/detail_question/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "detailQuestion": "test detail question?",
    "choices": ["q1","q2","q3"]
}

###
GET http://localhost:8000/detail_question/create
Authorization: Bearer addAccessTokenHere

###
GET http://localhost:8000/detail_question/getAllDetailQuestions
Authorization: Bearer addAccessTokenHere

#Answer----------------------------------------------------------------------

###
POST http://localhost:8000/answer/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "answer": "test answer",
    "pollId": "test poll id",
    "pollQuestionId": "test poll question id",
    "accountId": "test poll question id"
}

###
GET http://localhost:8000/answer/getAnswerById/_id
Authorization: Bearer addAccessTokenHere

###
GET http://localhost:8000/answer/getAnswersByPollId/pollId
Authorization: Bearer addAccessTokenHere