###
GET https://localhost:8000/

#Auth----------------------------------------------------------------------

###
POST https://localhost:8000/auth/register
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "Test1234@"
}

###
GET https://localhost:8000/auth/register

###
POST https://localhost:8000/auth/login
Content-Type: application/json

{
    "email" : "test@test.com",
    "password" : "Test1234@"
}

###
GET https://localhost:8000/auth/login

###
POST https://localhost:8000/auth/logout
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
"refreshToken": "addRefreshTokenHere"
}

###
GET https://localhost:8000/auth/logout
Authorization: Bearer addAccessTokenHere

###
POST https://localhost:8000/auth/refreshToken
Content-Type: application/json

{
"refreshToken": "addRefreshTokenHere"
}

###
PUT https://localhost:8000/auth/update
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "account id",
    "address": "Tel Aviv",
    "name": "test",
    "gender": "Male"
}

###
PUT https://localhost:8000/auth/updatePassword
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "account id",
    "oldPassword": "Test1234@",
    "newPassword": "Test1234!"
}

###
GET https://localhost:8000/auth/getAccountById/_id
Authorization: Bearer addAccessTokenHere

###
POST  https://localhost:8000/auth/facebook
Content-Type: application/json

{
    "facebookId": "1231231234",
    "email": "test1@test.com",
    "name": "test name"
}

#Poll----------------------------------------------------------------------

###
POST https://localhost:8000/poll/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "pollName": "poll name",
    "accountId": "4eb6e7e7e9b7f4194e000003",
    "pollQuestions": ["4eb6e7e7e9b7f4194e000004"]
}

###
GET https://localhost:8000/poll/create
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/poll/getAllPolls
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/poll/getPollsByClientId/accountId
Authorization: Bearer addAccessTokenHere


###
GET https://localhost:8000/poll/getPollsByUserId/accountId
Authorization: Bearer addAccessTokenHere

###
PUT https://localhost:8000/poll/update
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "account id",
    "gender": ["Male"]
}


#PollQuestion----------------------------------------------------------------------

###
POST https://localhost:8000/poll_question/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "pollQuestion": "test question?",
    "pollQuestionType": "Multi Choice",
    "choices": ["q1","q2","q3"],
    "pollId": "62750ff36cf117f40010803b"
}

###
GET https://localhost:8000/poll_question/create
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/poll_question/getPollQuestionsByPollId/pollId
Authorization: Bearer addAccessTokenHere

#Detail----------------------------------------------------------------------

###
POST https://localhost:8000/detail/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "_id": "4eb6e7e7e9b7f4194e000003",
    "answer": "test answer",
    "question": "test question?",
    "questionId": "test question id",
    "accountId": "account id"
}

###
GET https://localhost:8000/detail/getDetailsByAccountId/accountId
Authorization: Bearer addAccessTokenHere

#DetailQuestion----------------------------------------------------------------------

###
POST https://localhost:8000/detail_question/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "detailQuestion": "test detail question?",
    "choices": ["q1","q2","q3"]
}

###
GET https://localhost:8000/detail_question/create
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/detail_question/getAllDetailQuestions
Authorization: Bearer addAccessTokenHere

#Answer----------------------------------------------------------------------

###
POST https://localhost:8000/answer/create
Authorization: Bearer addAccessTokenHere
Content-Type: application/json

{
    "answer": "test answer",
    "pollId": "5da135bd61a1dd3e9c2a6e81",
    "pollQuestionId": "5da135bd61a1dd3e9c2a6e81",
    "accountId": "5da135bd61a1dd3e9c2a6e81"
}

###
GET https://localhost:8000/answer/getAnswerById/_id
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/answer/getAnswersByPollId/pollId
Authorization: Bearer addAccessTokenHere

###
GET https://localhost:8000/answer/getAnswersByPollQuestionId/pollQuestionId
Authorization: Bearer addAccessTokenHere
